### ISSUE TITLE
Fork for Troubleshooting

### ISSUE THREAD

**Issue by 321polorex123** [VakhtinAndrey/lis-save-editor#1]
Hey

Awesome work you did with the save editor!
I allowed myself to fork your repo to make kind of a troubleshooting tool. I hope this is okay with you.
(see http://steamcommunity.com/app/319630/discussions/1/458606877308441781/ for details)

Greetings and keep up the good work :)

**Comment by VakhtinAndrey** [comment]
Hi @321polorex123 and thanks!
Sure, you are free to do whatever helps the community. It would be great if my tool will be helpful for someone.

**Comment by 321polorex123** [comment]
Hey @VakhtinAndrey 
I finished the tool, for details see http://steamcommunity.com/app/319630/discussions/1/412448158166899451/
Have a nice day. :)

**Comment by VakhtinAndrey** [comment]
@321polorex123, nice work! Good luck!
P.S.

> I also want to thank the user Vakhtin Andrey[github.com], who put weeks of his/hers spare time into the safe editor which I use in the program.

His :)

**Comment by 321polorex123** [comment]
Time will tell if it works. A few already reported a success.

Corrected the post and credits section. I'm not good with foreign names. :/

**Comment by VakhtinAndrey** [comment]
It's OK, no problems.
Have one question: why do you always call save as 'safe'?

**Comment by 321polorex123** [comment]
Wait, did I... dammit.
If you'll excuse me, I will be busy renaming stuff for the rest of the evening (or at least what's left of it).

Thanks for the hint.

**Comment by VakhtinAndrey** [comment]
Haha! Don't take in mind ;) 
Not a big problem, just was woundering.

**Comment by 321polorex123** [comment]
Sight, fixed it.
