### ISSUE TITLE
System.FormatException

### ISSUE THREAD

**Issue by okkdev** [VakhtinAndrey/lis-save-editor#2]
System.FormatException when saving.
`System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
   bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   bei LifeIsStrangeSaveEditor.Win.MainForm.FillSaveData() in C:\Users\\Desktop\GitHub\lis-save-editor\LifeIsStrangeSaveEditor.Win\MainForm.cs:Zeile 224.
   bei LifeIsStrangeSaveEditor.Win.MainForm.SezializeSaveFile(Stream stream, SaveFile save) in C:\Users\\Desktop\GitHub\lis-save-editor\LifeIsStrangeSaveEditor.Win\MainForm.cs:Zeile 146.
   bei LifeIsStrangeSaveEditor.Win.MainForm.btnSave_Click(Object sender, EventArgs e) in C:\Users\\Desktop\GitHub\lis-save-editor\LifeIsStrangeSaveEditor.Win\MainForm.cs:Zeile 812.
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`
Can't save because of that.
I know its an old project, but I can't figure out what is causing the exception.

**Comment by VakhtinAndrey** [comment]
Hi. Seems like a number from some input cannot be converted to integer value. Did you change any values or just trying to save original file?

**Comment by okkdev** [comment]
It crashes whenever I try to save. Doesn't matter if I changed anything or not.
Does it work when you use it?
Do you want my savefile to debug?

**Comment by VakhtinAndrey** [comment]
Yep, you may show your file

**Comment by okkdev** [comment]
here you go:
https://drive.google.com/open?id=0B0pdMIFg5DhDb3V3VllNbFNPNkU

**Comment by VakhtinAndrey** [comment]
Share it to everyone who has a link. I can't download.

**Comment by okkdev** [comment]
sorry, forgot to change the permissions, it should work now.

**Comment by VakhtinAndrey** [comment]
The error occurs because checkpoint rotation somehow became empty (Misc -> Checkpoint rotation).
Workaround: write any 3 integers there (for example  Pitch = 0, Yaw = 0, Roll = 0) or just play for a few minutes until new checkpoint. Game should write correct values in this case.

**Comment by okkdev** [comment]
oh i see, thanks. 👍
